## Dynamically Typed Language

Python _dynamically infers_ the type of any variable being declared.

In [1]:
x = 4
print(x)
x = "four"
print(x)
# This code works, since Python is dynamically typed.

4
four


**Python is implemented in C.**<br>
Therefore, _every Python object is a cleverly-disguised C Structure._

The structure contains the value and supplementary information about the Python object.<br>
This means that there is some overhead in storing an integer in Python as compared to an integer in a compiled language like C.

A C integer is essentially a _label for a position in memory whose bytes encode an integer value._<br>
A Python integer is a _pointer to a position in memory containing all the Python object information, including the bytes that contain the integer value._<br>
This extra information in the Python integer structure is what allows Python to be coded so freely and dynamically.


## Python Collections
By default, a collection in Python is an instance of a **List**.
Because of Python's dynamic typing, we can create homogenous and heterogenous lists without any issues.

In [2]:
a = [1, 2, 3, 4]
print("Default collection type in Python is ", str(type(a)))
l = list(range(10))
print("List of numbers from a given range", l)
s = [str(c) for c in l]
print("List of strings", s)
h = [True, False, "2", 1]
print("An example of a heterogenous list", h)

Default collection type in Python is  <class 'list'>
List of numbers from a given range [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
List of strings ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']
An example of a heterogenous list [True, False, '2', 1]


This flexibility comes at a cost:<br>
To allow these flexible types, each item in a list contains its own type info, reference count, and other information.<br>
=> **Each item is a complete Python object.**

In the special case that all variables are of the same type, much of this important is redundant.<br>
=> **It can be much more efficient to store data in a fixed-type array.**

At the implementation level, the array essentially contains a single pointer to a contiguous block of data.<br>
The Python List contains a pointer to a block of pointers, which in-turn point to full Python objects. <br>
**Therefore, the list is flexible and sparse.** (Increased flexibility but lower performance).

The built-in `array` module (available since Python 3.3) can be used to create dense arrays of a uniform type:

In [3]:
import array
arr = array.array("i", l) # The 'i' specifies the type of the elements in the array.
print(arr)

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


## NumPy Arrays
Much more useful, however, is the `ndarray` object of the NumPy package.<br>
While Python's array object provides efficient storage of array-based data, NumPy adds to this **efficient operations on that data.**<br>
Unlike Python lists, NumPy is constrained to arrays that all contain the same type. If types do not match, **NumPy will upcast if possible**

In [4]:
import numpy as np
npArr1 = np.array([1, 4, 2, 3, 5])
print(npArr1.dtype) #int32

npArr2 = np.array([np.pi, 3, 4])
print(npArr2.dtype) #float64 because of pi being in the array

npArr3 = np.array([1, 2, 3, 4], dtype="float32")
print(npArr3.dtype) #float32 since we specified it while creating the array

int32
float64
float32


## Creating Arrays from scratch

We can create arrays from scratch using routines built into NumPy.

In [9]:
# Create a length-10 integer array filled with zeroes.
zeros = np.zeros(10, dtype="int")
print("Length 10 array of zeros", zeros)

# Create a 3x5 floating-point array filled with ones.
ones3x5 = np.ones((3, 5), dtype="float")
print("3x5 matrix of ones:\n", ones3x5, "\n", "dtype:", ones3x5.dtype)

# Create a 3x5 array filled with pi
pi3x5 = np.full((3, 5), np.pi)
print("3x5 matrix of pi\n", pi3x5, "\n", "dtype:", pi3x5.dtype)

# Create an array filled with a linear sequence starting at 0, ending at 20 exclusive, with a step of 2
step2Sequence = np.arange(0, 20, 2, dtype="int")
print("Array of linear sequence starting at 0, ending at 20 exclusive:\n", step2Sequence, "\ndtype:", step2Sequence.dtype, ". itemsize: ", step2Sequence.itemsize, "bytes. nBytes:", step2Sequence.nbytes)

# Create an evenly-spaced sequence between 0 and 1 consisting of 5 values
linSpace = np.linspace(0, 1, 5)
print("Evenly-spaced sequence of 5 values between 0 & 1:\n", linSpace)

# Create a 3x3 identity matrix
id3x3 = np.eye(3)
print("3x3 Identity Matrix:\n", id3x3)

# Create a normal distribution with mean 0 and Standard Deviation at 1
# 3x3 matrix
normal3x3 = np.random.normal(0, 1, (3, 3))
print(normal3x3)
print("No of dimensions:", normal3x3.ndim)
print("Item size:", normal3x3.itemsize, "bytes. size: ", normal3x3.size, "nBytes: ", normal3x3.nbytes)


Length 10 array of zeros [0 0 0 0 0 0 0 0 0 0]
3x5 matrix of ones:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] 
 dtype: float64
3x5 matrix of pi
 [[3.14159265 3.14159265 3.14159265 3.14159265 3.14159265]
 [3.14159265 3.14159265 3.14159265 3.14159265 3.14159265]
 [3.14159265 3.14159265 3.14159265 3.14159265 3.14159265]] 
 dtype: float64
Array of linear sequence starting at 0, ending at 20 exclusive:
 [ 0  2  4  6  8 10 12 14 16 18] 
dtype: int32 . itemsize:  4 bytes. nBytes: 40
Evenly-spaced sequence of 5 values between 0 & 1:
 [0.   0.25 0.5  0.75 1.  ]
3x3 Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[-0.79193222 -0.20074164  1.32986613]
 [ 1.0579304  -0.83371229  0.2821077 ]
 [ 0.44989668 -0.11144876  0.51313419]]
No of dimensions: 2
Item size: 8 bytes. size:  9 nBytes:  72
