### Array Indexing
1. In a 1D array, the i<sup>th</sup> value can be accessed by specifying the desired index in square brackets.
2. In a multi-dimensional array, items can be accessed by using **comma-separated indices**.

To index from the end of the array, we can use negative indices.

In [1]:
import numpy as np

In [7]:
x1 = np.array([5, 0, 1]) # 1D Array
print("x1[0] = ", x1[0])
print("x1[-1] = ", x1[-1])

x2 = np.array(
    [[3, 5, 2, 4],
    [7, 6, 8, 8],
    [1, 6, 7, 7]]
) # 2D array of shape (3, 4)

print("x2[0][0] = ", x2[0][0]) # Using conventional multi-dimensional indexing
print("x2[0, 0] = ", x2[0, 0]) # Using Python-special multi-dimensional indexing
print("x2[0, -1] = ", x2[0, -1])

x1[0] =  5
x1[-1] =  1
x2[0][0] =  3
x2[0, 0] =  3
x2[0, -1] =  4


### Modifying Values
Values can also be modified using any of the above index notations.<br>
Keep in mind that, unlike Python lists, NumPy arrays have a fixed type. So whenever you try to insert mismatching types of values, either the value will be silently converted to match the type of the existing array, or the insert operation will throw an error.<br>
For example, if we try to insert a floating point value into an integer array, the value being inserted will be silently truncated to an integer.

In [14]:
x1[0] = np.pi
print(x1) # x1[0] got truncated to 3.
try:
    x1[0] = "Hello" # Throws a ValueError
except Exception as e:
    print(e)
x2[0, 0] = 12
print(x2)

[3 0 1]
invalid literal for int() with base 10: 'Hello'
[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


### Array Slicing: Accessing Sub-arrays.
Just as we can use square brackets to access individual array elements, we can also use them to access subarrays with the slice notation, marked by the colon (:) character. 
The NumPy slicing syntax follows that of the standard Python list; to access a slice of an array x, use this:

`x[start:stop:step]`

If any of these are unspecified, they default to the values `start=0`, `stop=size of dimension`, `step=1`. 

When the `step` value is negative, **the defaults for start and stop are swapped**.

**An important point to note** is that the array slices return _views_ rather than _copies_ of the array data. 
- In lists, slicing will return copies.
- In NumPy arrays, slices will return views.
**Modifying a slice of an array modifies the array in-place**.

In [21]:
x = np.arange(10)
print(x[:5]) # First 5 elements
print(x[4:7]) # Elements with index 4, 5, 6 (7 exclusive)
print(x[5:]) # Elements starting with index 5 inclusive
print(x[::2]) # Every other element
print(x[1::2])  # every other element, starting at index 1
print(x[::-1]) # Reversed array with step count -1
print(x[5::-2]) # Every other element from index 5 inclusive, reversed

[0 1 2 3 4]
[4 5 6]
[5 6 7 8 9]
[0 2 4 6 8]
[1 3 5 7 9]
[9 8 7 6 5 4 3 2 1 0]
[5 3 1]


In [24]:
x2 = np.array([
    [12,  5,  2,  4],
    [ 7,  6,  8,  8],
    [ 1,  6,  7,  7]
])

print(x2[:2, :3]) # First two rows, first three columns
print(x2[:, 1]) # All rows, 2nd column
print(x2[0, :]) # First row
print(x2[::-1, ::-1]) # Entire matrix, reversed

[[12  5  2]
 [ 7  6  8]]
[5 6 6]
[12  5  2  4]
[[ 7  7  6  1]
 [ 8  8  6  7]
 [ 4  2  5 12]]


In [26]:
# No copy views
x2Sub = x2[:2, :2] # Extract the first two rows and columns of x2 into x2Sub.
# Note that x2Sub is just a view of x2. Modifying x2Sub will modify x2
x2Sub[0, 0] = 10

print("x2Sub:\n", x2Sub)
print("x2:\n", x2)

# We can make a proper copy of an array using the "copy()" method built into np arrays.
x2Copy = x2[:2, :2].copy()
x2Copy[0, 0] = 5
print("x2 copy:\n", x2Copy)
print("x2:\n", x2)

x2Sub:
 [[10  5]
 [ 7  6]]
x2:
 [[10  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]
x2 copy:
 [[5 5]
 [7 6]]
x2:
 [[10  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


### Array Reshaping

Another useful type of operation is reshaping of arrays. The most flexible way of doing this is with the `reshape` method. <br>
For this to work, **the size of the initial array must match the size of the reshaped array**. <br>
Where possible, the reshape method will use a no-copy view of the initial array, but with non-contiguous memory buffers this is not always the case.

In [28]:
x = np.array([1, 2, 3])

# row vector via reshape
x.reshape((1, 3))
print(x)
# column vector via reshape
x.reshape((3, 1))

[1 2 3]


array([[1],
       [2],
       [3]])